#!/bin/bash

echo "======================================"
echo "  Jenkins Job Setup for Multi-Cloud  "
echo "======================================"
echo ""
echo "Your Jenkins is already running at http://localhost:8080"
echo ""
echo "To set up the Terraform pipeline:"
echo ""
echo "1. Open: http://localhost:8080"
echo ""
echo "2. Click 'New Item'"
echo ""
echo "3. Enter name: terraform-multicloud"
echo ""
echo "4. Select 'Pipeline' → OK"
echo ""
echo "5. Configure:"
echo "   - Definition: Pipeline script from SCM"
echo "   - SCM: Git"
echo "   - Repository URL: https://github.com/Raj-glitch-max/Terraform-MultiCloud-Infrastructure.git"
echo "   - Branch: */master"
echo "   - Script Path: Jenkinsfile"
echo ""
echo "6. Click 'Save'"
echo ""
echo "7. Click 'Build Now'"
echo ""
echo "======================================"
echo ""
echo "Your Jenkinsfile is ready at:"
echo "$(pwd)/Jenkinsfile"
echo ""
echo "Project GitHub:"
echo "https://github.com/Raj-glitch-max/Terraform-MultiCloud-Infrastructure"
echo ""
